### ISSUE TITLE
Question regarding the time measurement

### ISSUE THREAD

**Issue by wsong83** [comparch-security/cpu-sec-bench#119]
https://github.com/comparch-security/cpu-sec-bench/blob/2a1389edfb6526406d74cd7326104677a0585e65/scheduler/run-test.cpp#L431

I am confused. Why the `stop` stamp is recorded after a process is created? In this way, `stop - start` counts only the time required to create a process rather than how long the process actually runs.

Intentional? Or a mistake?

@zintown

**Comment by zintown** [comment]
When the `posix_spawnp()` function is finished, the corresponding test case(e.g., test/acc-check-data-pointer-arithmetic) is also run over.  So, I place the `stop` stamp after `posix_spawnp()` intentionally.
