### ISSUE TITLE
cpi test error

### ISSUE THREAD

**Issue by zintown** [comparch-security/cpu-sec-bench#23]
==678025==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.

Oddly, CXXFLAGS doesn't include -fsanitizer=address, and it's not a specific test's error.
Although this error happens in the last test unit in cpi test collection.

**Comment by zintown** [comment]
========== cpi-modify-GOT =========
make test/cpi-modify-GOT
g++ -I./lib -O2 -std=c++11 -Wall cpi/modify-GOT.cpp ./lib/common/global_var.o ./lib/common/signal.o ./lib/common/temp_file.o ./lib/x86_64/assembly.o -L. -Wl,-rpath,. -o test/cpi-modify-GOT -lcfi 

test/cpi-modify-GOT 1

========== cpi-read-vtable-pointer =========
make test/cpi-read-vtable-pointer
g++ -I./lib -O2 -std=c++11 -Wall cpi/read-vtable-pointer.cpp ./lib/common/global_var.o ./lib/common/signal.o ./lib/common/temp_file.o ./lib/x86_64/assembly.o -L. -Wl,-rpath,. -o test/cpi-read-vtable-pointer -lcfi 
/usr/bin/ld: /lib/x86_64-linux-gnu/libasan.so.6: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/usr/bin/ld: /lib/x86_64-linux-gnu/libasan.so.6: warning: the use of `tempnam' is dangerous, better use `mkstemp'
/usr/bin/ld: /lib/x86_64-linux-gnu/libasan.so.6: warning: the use of `tmpnam_r' is dangerous, better use `mkstemp'

test/cpi-read-vtable-pointer
==680008==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
Test abnormality: cpi-read-vtable-pointer failed with unexpected exit value 1
Test abnormality: cpi-read-vtable-pointer failed with unexpected exit value 1

**Comment by zintown** [comment]
ciyan@newport:~/phd_proj/cpu-sec-bench$ ldd ./test/cpi-read-vtable-pointer 
        linux-vdso.so.1 (0x00007ffe3a5e9000)
        libcfi.so => ./libcfi.so (0x00007f6061822000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f60615e2000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f60615c2000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f606139a000)
        libasan.so.6 => /lib/x86_64-linux-gnu/libasan.so.6 (0x00007f60609b1000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f60608c8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6061831000)
ciyan@newport:~/phd_proj/cpu-sec-bench$ ldd ./test/cpi-modify-GOT 
        linux-vdso.so.1 (0x00007ffd8d6ce000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f9b1e32a000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9b1e30a000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9b1e0e2000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9b1dffb000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9b1e573000)

**Comment by wsong83** [comment]
ready to be closed? @zintown

**Comment by zintown** [comment]
Yes, I forgot to close it.
